'use client'

import { useState } from 'react'
import { Crown, Flame, Gift, Grid2X2, Headphones, Home, Menu, Search, ShieldCheck, Sparkles, Trophy, UserRound, WalletCards, X, Zap, Volleyball, ChevronRight, CircleHelp, MessageCircle, Settings, LogOut, Heart, History, Star } from 'lucide-react'

const games = [
  { name: 'Fortune Tiger', type: 'Slots', rating: '4.9', image: '/games/fortune-tiger.png' }, { name: 'Fortune Rabbit', type: 'Slots', rating: '4.8', image: '/games/fortune-rabbit.png' }, { name: 'Dragon Gold', type: 'Arcade', rating: '4.7', image: '/games/dragon-gold.png' }, { name: 'Golden Fortune', type: 'Clássicos', rating: '4.9', image: '/games/golden-fortune.png' }, { name: 'Mystic Gems', type: 'Puzzle', rating: '4.6', image: '/games/mystic-gems.png' }, { name: 'Royal Spin', type: 'Cassino', rating: '4.8', image: '/games/royal-spin.png' }, { name: 'Neon Roulette', type: 'Cassino', rating: '4.8', image: '/games/neon-roulette.png' }, { name: 'Cosmic Crystals', type: 'Puzzle', rating: '4.7', image: '/games/cosmic-crystals.png' }, { name: 'Cyber Cards', type: 'Cartas', rating: '4.6', image: '/games/cyber-cards.png' }, { name: 'Treasure Chest', type: 'Aventura', rating: '4.9', image: '/games/treasure-chest.png' }, { name: 'Lightning Dice', type: 'Arcade', rating: '4.8', image: '/games/lightning-dice.png' },
]
const categories = [{ name: 'Popular', icon: Flame }, { name: 'Esportes', icon: Volleyball }, { name: 'Jogos', icon: Grid2X2 }, { name: 'Slots', icon: Sparkles }, { name: 'Promoções', icon: Gift }]
const navItems = [{ id: 'inicio', label: 'Início', icon: Home }, { id: 'promocoes', label: 'Promoções', icon: Gift }, { id: 'jogos', label: 'Jogos', icon: Grid2X2 }, { id: 'suporte', label: 'Suporte', icon: Headphones }, { id: 'perfil', label: 'Perfil', icon: UserRound }]

type Game = typeof games[number]
function GameGrid({ items }: { items: Game[] }) { return <div className="games-grid">{items.map((game, index) => <article className="game-card" key={game.name}><div className="game-art"><img src={game.image} alt={`Capa ilustrativa de ${game.name}`} /><div className="game-index">0{index + 1}</div><span className="play-pill">DEMO</span></div><div className="game-info"><div><h3>{game.name}</h3><p>{game.type}</p></div><span className="rating">★ {game.rating}</span></div></article>)}</div> }
function Section({ eyebrow, title, items }: { eyebrow: string; title: string; items: Game[] }) { return <section className="content-section"><div className="section-heading"><div><span className="section-kicker">{eyebrow}</span><h2>{title}</h2></div><button className="view-all" type="button">Ver todos <ChevronRight /></button></div><GameGrid items={items} /></section> }
function PageHeader({ title, eyebrow }: { title: string; eyebrow: string }) { return <div className="internal-header"><span className="section-kicker">{eyebrow}</span><h1>{title}</h1><p>Explore uma experiência demonstrativa feita para você.</p></div> }

function HomePage({ go }: { go: (id: string) => void }) { return <>
  <section id="inicio" className="hero-section"><div className="hero-copy"><div className="eyebrow"><Sparkles /> EXPERIÊNCIA ROYALBET</div><h1>Jogue com<br /><span>mais estilo.</span></h1><p>Uma seleção de entretenimento premium para você explorar no seu ritmo.</p><button className="primary-button" type="button" onClick={() => go('jogos')}>Explorar jogos <Zap /></button><div className="hero-note"><ShieldCheck /> Interface demonstrativa · Sem apostas reais</div></div><div className="hero-pagination"><span className="selected" /><span /><span /></div></section>
  <section className="promo-grid" aria-label="Promoções demonstrativas">{[['NOVIDADE','Clube','Neon','promo-purple'],['DESTAQUE','Golden','Nights','promo-gold'],['EXCLUSIVO','Royal','Play','promo-blue']].map(([label, first, second, cls], i) => <article className={`promo-card ${cls}`} key={label}><div><span className="promo-label">{label}</span><h2>{first}<br />{second}</h2><button type="button" onClick={() => go('promocoes')}>Conhecer <ChevronRight /></button></div><div className="promo-orb"><Sparkles /></div></article>)}</section>
  <section className="category-bar" aria-label="Categorias de jogos">{categories.map(({ name, icon: Icon }) => <button key={name} type="button" onClick={() => go(name === 'Promoções' ? 'promocoes' : 'jogos')}><Icon /> <span>{name}</span></button>)}</section>
  <Section eyebrow="SELEÇÃO ROYALBET" title="Popular" items={games.slice(0, 6)} />
  <div className="mid-promo"><div><span>EXPERIÊNCIA DEMO</span><strong>Descubra seu próximo favorito</strong></div><Sparkles /></div>
  <Section eyebrow="ACABOU DE CHEGAR" title="Novidades" items={games.slice(6, 9)} />
  <section className="benefits-section"><div className="section-heading"><div><span className="section-kicker">POR QUE ROYALBET</span><h2>Feito para você</h2></div></div><div className="benefits-grid"><div className="benefit"><span className="benefit-icon"><Zap /></span><h3>Experiência fluida</h3><p>Navegação rápida e intuitiva em qualquer tela.</p></div><div className="benefit"><span className="benefit-icon blue"><Trophy /></span><h3>Jogos selecionados</h3><p>Curadoria de títulos para todos os estilos.</p></div><div className="benefit"><span className="benefit-icon purple"><ShieldCheck /></span><h3>Ambiente seguro</h3><p>Diversão responsável em um espaço demonstrativo.</p></div></div></section>
</> }

function PromotionsPage({ go }: { go: (id: string) => void }) { return <div className="internal-page"><PageHeader eyebrow="ROYALBET CLUB" title="Promoções" /><div className="promo-hero"><div><span className="promo-label">EXPERIÊNCIA DEMO</span><h2>Mais estilo para<br /><b>cada descoberta.</b></h2><p>Ofertas visuais e benefícios fictícios para deixar sua jornada mais divertida.</p><button className="primary-button" onClick={() => go('jogos')}>Explorar jogos <Zap /></button></div><Gift /></div><div className="offer-grid">{[['Bônus de boas-vindas','Um presente visual para começar sua jornada.','+100%'],['Clube Royal','Conteúdos selecionados para membros demo.','VIP'],['Noite Neon','Cores, novidades e muita diversão.','NEON']].map(([title, text, tag]) => <article className="offer-card" key={title}><span>{tag}</span><h3>{title}</h3><p>{text}</p><button type="button">Conhecer promoção <ChevronRight /></button></article>)}</div><Section eyebrow="ESCOLHAS DA SEMANA" title="Destaques" items={games.slice(0, 3)} /><div className="benefits-section promo-benefits"><div className="section-heading"><div><span className="section-kicker">VANTAGENS</span><h2>Benefícios Royalbet</h2></div></div><div className="benefits-grid"><div className="benefit"><span className="benefit-icon"><Crown /></span><h3>Seleção premium</h3><p>Uma curadoria visual especial.</p></div><div className="benefit"><span className="benefit-icon purple"><Sparkles /></span><h3>Novidades sempre</h3><p>Descubra novos mundos fictícios.</p></div></div></div></div> }

function GamesPage() { const [query, setQuery] = useState(''); const filtered = games.filter(g => g.name.toLowerCase().includes(query.toLowerCase())); return <div className="internal-page"><PageHeader eyebrow="CATÁLOGO DEMO" title="Jogos" /><div className="search-box"><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar jogo" aria-label="Buscar jogo" /></div><div className="catalog-tabs"><button className="active">Popular</button><button>Novidades</button><button>Mais jogados</button><button>Slots</button><button>Cassino</button><button>Jogos</button></div><Section eyebrow="TODOS OS TÍTULOS" title="Catálogo completo" items={filtered} /></div> }

function SupportPage() { return <div className="internal-page"><PageHeader eyebrow="ESTAMOS AQUI" title="Central de ajuda" /><div className="support-cards"><article><CircleHelp /><h3>Perguntas frequentes</h3><p>Encontre respostas rápidas para as dúvidas mais comuns.</p><button type="button">Ver perguntas <ChevronRight /></button></article><article><MessageCircle /><h3>Fale conosco</h3><p>Nossa equipe demo está pronta para orientar você.</p><button type="button">Iniciar conversa <ChevronRight /></button></article><article><ShieldCheck /><h3>Jogo responsável</h3><p>Informações claras sobre esta experiência demonstrativa.</p><button type="button">Saiba mais <ChevronRight /></button></article></div><div className="faq-list"><span className="section-kicker">DÚVIDAS COMUNS</span>{['Como funciona a experiência demonstrativa?','A ROYALBET realiza pagamentos?','Onde encontro meus jogos favoritos?'].map(q => <button type="button" key={q}><span>{q}</span><ChevronRight /></button>)}</div></div> }

function ProfilePage() { return <div className="internal-page"><PageHeader eyebrow="MINHA ÁREA" title="Perfil" /><div className="profile-card"><div className="avatar"><UserRound /></div><div><h2>Alex Royal</h2><p>membro demonstrativo</p></div><span className="profile-level">NÍVEL 08</span></div><div className="profile-actions"><button><History /><span>Histórico<br /><small>Atividade demo</small></span></button><button><Heart /><span>Favoritos<br /><small>6 jogos salvos</small></span></button><button><Settings /><span>Configurações<br /><small>Preferências</small></span></button></div><div className="history-card"><div className="section-heading"><div><span className="section-kicker">RECENTES</span><h2>Histórico demonstrativo</h2></div></div>{games.slice(0, 3).map(game => <div className="history-row" key={game.name}><img src={game.image} alt="" /><span><b>{game.name}</b><small>Explorado recentemente</small></span><Star /></div>)}</div><button className="logout-button" type="button"><LogOut /> Sair da demonstração</button></div> }

export default function Page() { const [active, setActive] = useState('inicio'); const [menuOpen, setMenuOpen] = useState(false); const go = (id: string) => { setActive(id); setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }; const current = navItems.find(item => item.id === active) ?? navItems[0]; return <main className="min-h-screen overflow-x-hidden bg-[#070912] text-white"><div className="site-shell"><header className="topbar"><button className="brand brand-button" onClick={() => go('inicio')} aria-label="Ir para início"><span className="brand-mark"><Crown /></span><span>ROYAL<span>BET</span></span></button><nav className="desktop-nav" aria-label="Navegação principal">{navItems.slice(0, 4).map(item => <button className={active === item.id ? 'active' : ''} key={item.id} onClick={() => go(item.id)}>{item.label}</button>)}</nav><div className="header-actions"><div className="demo-balance"><WalletCards /><span><small>Saldo demonstrativo</small><strong>R$ 1.250,00</strong></span></div><button className="login-button" type="button">Entrar</button><button className="menu-button" type="button" aria-label="Abrir menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div></header>{menuOpen && <aside className="side-panel"><div className="side-title"><span>MENU</span><X onClick={() => setMenuOpen(false)} /></div>{navItems.map(item => { const Icon = item.icon; return <button key={item.id} onClick={() => go(item.id)} className={active === item.id ? 'active' : ''}><Icon />{item.label}</button> })}</aside>}<div className="page-content">{active === 'inicio' && <HomePage go={go} />}{active === 'promocoes' && <PromotionsPage go={go} />}{active === 'jogos' && <GamesPage />}{active === 'suporte' && <SupportPage />}{active === 'perfil' && <ProfilePage />}</div><footer className="footer"><div className="brand"><span className="brand-mark"><Crown /></span><span>ROYAL<span>BET</span></span></div><p>Entretenimento premium, do seu jeito.</p><small>© 2025 ROYALBET · Interface demonstrativa para fins de apresentação.</small></footer></div><nav className="bottom-nav" aria-label="Navegação mobile">{navItems.map(item => { const Icon = item.icon; return <button className={active === item.id ? 'selected' : ''} key={item.id} onClick={() => go(item.id)}><Icon /><span>{item.label}</span></button> })}</nav></main> }
